/**
 * The things living on the roof.
 *
 * Everything else that moves out here is weather or machinery — wind, steam, a
 * plane crossing, windows switching. All of it is indifferent to you, and a
 * place where nothing notices you read as a diorama however much of it is
 * moving. These are the things that *react*: pigeons that scatter when you get
 * too close and settle again once you have gone, and moths that will not leave
 * a lamp alone.
 *
 * TWO OF THE THREE NEED NO ART. Moths are two-pixel flecks and pigeons are the
 * same little strokes the startled flock is already drawn with, so they cost a
 * few dozen lines rather than a generation run. Only the cat is a sprite.
 *
 * Moths need no MANIFEST data either: they orbit whatever props declare a
 * `light`, so every lamp in the world got moths the moment this existed, and
 * any lamp added later gets them for free.
 */

/** Deterministic PRNG. A roof that behaves differently every load is noise. */
function rng(seed) {
    let a = seed >>> 0;
    return () => {
        a = (a + 0x6D2B79F5) >>> 0;
        let t = Math.imul(a ^ (a >>> 15), 1 | a);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

export class Critters {
    /**
     * @param {object} manifest
     * @param {object} [opts]
     * @param {number} [opts.seed]
     */
    constructor(manifest, { seed = 20260823 } = {}) {
        this.manifest = manifest;
        this.rand = rng(seed);
        this.t = 0;

        const spec = manifest.critters || {};

        // ── Moths, derived from the lights that already exist ─────────
        const perLight = spec.mothsPerLight != null ? spec.mothsPerLight : 2;
        this.moths = [];
        for (const p of manifest.props) {
            // Not every light is a lamp. A neon sign or a moon has `pool: false`
            // and is not something an insect can be circling.
            if (!p.light || p.light.pool === false) continue;
            if (p.plane !== manifest.actorPlane) continue;

            const n = Math.round(perLight * (0.5 + this.rand()));
            for (let i = 0; i < n; i++) {
                this.moths.push({
                    x: p.x,
                    z: p.z != null ? p.z : 0.5,
                    oy: (p.light.oy || 0),
                    r: 10 + this.rand() * 22,
                    phase: this.rand() * Math.PI * 2,
                    speed: 0.7 + this.rand() * 1.4,
                    // A second, faster wobble so the orbit is not a clean circle.
                    wob: 1.8 + this.rand() * 2.6,
                    tone: p.light.color || [255, 220, 170]
                });
            }
        }

        // ── The cat ───────────────────────────────────────────────────
        //
        // The only thing on the roof with opinions about you. Three poses
        // rather than an animated sheet: a multi-frame walk cycle generated by
        // an image model drifts between frames, and a cat reads almost entirely
        // from its silhouette anyway.
        this.cat = spec.cat ? {
            x: spec.cat.x,
            z: spec.cat.z != null ? spec.cat.z : 0.3,
            home: spec.cat.x,
            roam: spec.cat.roam || [spec.cat.x - 400, spec.cat.x + 400],
            perches: spec.cat.perches || [],
            state: 'sleep',
            pose: 'curl',
            facing: -1,
            timer: 6 + this.rand() * 10,
            target: null,
            /** How long the player has stood still nearby. */
            stillFor: 0,
            lastPlayerX: null
        } : null;

        // ── Pigeons that actually live here ───────────────────────────
        this.flocks = (spec.pigeons || []).map((f, i) => ({
            id: f.id || `flock${i}`,
            home: f.x,
            z: f.z != null ? f.z : 0.35,
            spread: f.spread != null ? f.spread : 90,
            birds: []
        }));

        for (const f of this.flocks) {
            const n = f.spread > 0 ? (3 + Math.floor(this.rand() * 3)) : 3;
            for (let i = 0; i < n; i++) f.birds.push(this.makePigeon(f));
        }
    }

    makePigeon(f) {
        return {
            x: f.home + (this.rand() - 0.5) * f.spread * 2,
            z: f.z + (this.rand() - 0.5) * 0.12,
            /** 'ground' pecking about, or 'flying' after a scare. */
            state: 'ground',
            /** Countdown to the next peck or hop. */
            next: this.rand() * 3,
            hop: 0,
            phase: this.rand() * Math.PI * 2,
            vx: 0,
            vy: 0,
            flight: 0,
            face: this.rand() < 0.5 ? -1 : 1
        };
    }

    /** Every pigeon currently on the ground, across all flocks. */
    get grounded() {
        return this.flocks.flatMap(f => f.birds.filter(b => b.state === 'ground'));
    }

    /**
     * @param {number} dt
     * @param {number|null} playerX - world x of the character, or null
     */
    update(dt, playerX = null) {
        if (dt <= 0) return;
        this.t += dt;

        for (const m of this.moths) m.phase += dt * m.speed;
        this.updateCat(dt, playerX);

        for (const f of this.flocks) {
            for (const b of f.birds) {
                if (b.state === 'flying') {
                    b.flight += dt;
                    b.x += b.vx * dt;
                    b.y = (b.y || 0) + b.vy * dt;
                    b.vy += dt * 0.10;   // arc over and come back down

                    // Land a little further off, then carry on as before. They
                    // come back: a flock that scatters once and never returns
                    // leaves the roof emptier than before you arrived.
                    if (b.flight > 2.2 + this.rand() * 1.5) {
                        b.state = 'ground';
                        b.y = 0;
                        b.flight = 0;
                        b.next = 0.4 + this.rand() * 2;
                        b.x = Math.max(f.home - f.spread * 2.2,
                              Math.min(f.home + f.spread * 2.2, b.x));
                    }
                    continue;
                }

                // Scatter. Distance is checked per bird rather than per flock,
                // so the near edge goes up first and the far side a moment
                // later, which is how a real flock leaves.
                if (playerX != null && Math.abs(playerX - b.x) < 105) {
                    b.state = 'flying';
                    b.flight = 0;
                    b.y = 0;
                    b.vx = (b.x < playerX ? -1 : 1) * (60 + this.rand() * 90);
                    b.vy = -(0.16 + this.rand() * 0.12);
                    continue;
                }

                b.next -= dt;
                if (b.next > 0) continue;

                // Peck, or take a step. Mostly peck: a pigeon that is always
                // walking reads as agitated rather than as busy.
                if (this.rand() < 0.62) {
                    b.hop = 0.28;
                } else {
                    const step = (this.rand() - 0.5) * 34;
                    b.face = step < 0 ? -1 : 1;
                    b.x = Math.max(f.home - f.spread, Math.min(f.home + f.spread, b.x + step));
                }
                b.next = 0.5 + this.rand() * 2.4;
            }

            for (const b of f.birds) if (b.hop > 0) b.hop = Math.max(0, b.hop - dt);
        }
    }

    /**
     * The cat's own business, and its opinion of you.
     *
     * Left alone it sleeps, wakes, sits, and wanders to another perch. What
     * makes it read as alive is that it treats you as a fact about the world:
     * it wakes when you come near, gives ground if you crowd it, and — the part
     * worth having — comes over if you stand still long enough. Nothing else
     * out here rewards standing still.
     */
    updateCat(dt, playerX) {
        const c = this.cat;
        if (!c) return;

        // Stillness is inferred from the player's own position rather than
        // plumbed in, so this needs nothing from the game loop it does not
        // already get.
        if (playerX != null && c.lastPlayerX != null) {
            c.stillFor = Math.abs(playerX - c.lastPlayerX) < 0.5 ? c.stillFor + dt : 0;
        }
        c.lastPlayerX = playerX;

        const dist = playerX == null ? Infinity : Math.abs(playerX - c.x);

        // Crowded: give ground. Never runs — a cat that bolts reads as prey.
        if (dist < 95) {
            c.state = 'walk';
            c.pose = 'walk';
            const away = c.x < playerX ? -1 : 1;
            c.target = Math.max(c.roam[0], Math.min(c.roam[1], c.x + away * 220));
            c.timer = 4;
        } else if (c.state === 'sleep' && dist < 250) {
            c.state = 'sit';
            c.pose = 'sit';
            c.timer = 5 + this.rand() * 6;
        } else if (c.state === 'sit' && c.stillFor > 3.5 && dist < 420 && dist > 130) {
            // You waited. It comes over — but stops short, because it is a cat.
            c.state = 'walk';
            c.pose = 'walk';
            c.target = playerX + (c.x < playerX ? -110 : 110);
            c.timer = 6;
        }

        c.timer -= dt;

        if (c.state === 'walk') {
            const to = c.target != null ? c.target : c.x;
            const dx = to - c.x;
            if (Math.abs(dx) < 4 || c.timer <= 0) {
                c.state = 'sit';
                c.pose = 'sit';
                c.target = null;
                c.timer = 6 + this.rand() * 10;
            } else {
                c.facing = dx < 0 ? -1 : 1;
                c.x += Math.sign(dx) * 46 * dt;
            }
            return;
        }

        if (c.timer > 0) return;

        // Nothing prompted it, so it does something of its own accord.
        if (c.state === 'sit') {
            if (this.rand() < 0.45 && c.perches.length) {
                const p = c.perches[Math.floor(this.rand() * c.perches.length)];
                c.state = 'walk';
                c.pose = 'walk';
                c.target = p.x;
                c.z = p.z != null ? p.z : c.z;
                c.timer = 8;
            } else {
                c.state = 'sleep';
                c.pose = 'curl';
                c.timer = 12 + this.rand() * 20;
            }
        } else {
            c.state = 'sit';
            c.pose = 'sit';
            c.timer = 6 + this.rand() * 12;
        }
    }

    /** Puts every flock back on the ground at home. Used on a scene swap. */
    reset() {
        for (const f of this.flocks) {
            f.birds = f.birds.map(() => this.makePigeon(f));
        }
        if (this.cat) {
            this.cat.x = this.cat.home;
            this.cat.state = 'sleep';
            this.cat.pose = 'curl';
            this.cat.target = null;
            this.cat.stillFor = 0;
            this.cat.lastPlayerX = null;
        }
    }

    /**
     * Draws the ground flock. Called on the floor plane, before the props, so a
     * pigeon behind a crate is behind it.
     */
    drawPigeons(ctx, world, viewH) {
        const plane = world.plane(world.manifest.actorPlane) || { parallax: 1 };
        const look = world.lookOffset(plane);
        const unit = world.unit(viewH);

        ctx.save();
        for (const f of this.flocks) {
            for (const b of f.birds) {
                const sx = world.camera.toScreen(b.x, plane.parallax);
                const dScale = world.depthScale(b.z);
                const lift = world.liftFor(
                    world.terrain ? world.terrain.elevationAt(b.x, b.z) : 0, b.z, viewH);
                let sy = world.groundYFor(b.z, viewH) - lift + look;

                if (b.state === 'flying') {
                    sy += (b.y || 0) * viewH;
                    ctx.strokeStyle = 'rgba(20,22,40,0.85)';
                    ctx.lineWidth = 1.6;
                    const flap = Math.sin(b.flight * 15 + b.phase) * 3.2;
                    ctx.beginPath();
                    ctx.moveTo(sx - 5, sy + flap);
                    ctx.lineTo(sx, sy);
                    ctx.lineTo(sx + 5, sy + flap);
                    ctx.stroke();
                    continue;
                }

                // On the ground: a body block, a head, and a tail. Blocks rather
                // than curves, so it belongs to the same drawing as everything
                // else out here.
                const s = Math.max(1, Math.round(2.2 * unit * dScale));
                const peck = b.hop > 0 ? s : 0;
                ctx.fillStyle = 'rgba(30,32,54,0.92)';
                ctx.fillRect(Math.round(sx - s), Math.round(sy - s * 2), s * 2, s * 2);
                ctx.fillRect(Math.round(sx + b.face * s), Math.round(sy - s * 3 + peck), s, s);
                ctx.fillStyle = 'rgba(30,32,54,0.6)';
                ctx.fillRect(Math.round(sx - b.face * s * 2), Math.round(sy - s * 2), s, s);
            }
        }
        ctx.restore();
    }

    /** Draws the moths. Called after the props, so they pass in front of lamps. */
    drawMoths(ctx, world, viewH) {
        if (!this.moths.length) return;
        const plane = world.plane(world.manifest.actorPlane) || { parallax: 1 };
        const look = world.lookOffset(plane);
        const unit = world.unit(viewH);

        ctx.save();
        for (const m of this.moths) {
            const dScale = world.depthScale(m.z);
            const wob = Math.sin(m.phase * m.wob) * 0.4;
            const ox = Math.cos(m.phase) * m.r * (1 + wob);
            const oy = Math.sin(m.phase * 1.7) * m.r * 0.55;

            const sx = world.camera.toScreen(m.x, plane.parallax) + ox * unit * dScale;
            const lift = world.liftFor(
                world.terrain ? world.terrain.elevationAt(m.x, m.z) : 0, m.z, viewH);
            const sy = world.groundYFor(m.z, viewH) - lift + look
                - (m.oy + oy) * unit * dScale;

            // Blink out as they turn edge-on. A moth that is always visible
            // reads as a floating dot; one that flickers reads as wings.
            const a = 0.30 + 0.45 * Math.abs(Math.sin(m.phase * 3.1));
            const s = Math.max(1, Math.round(1.6 * unit * dScale));
            ctx.fillStyle = `rgba(${m.tone[0]},${m.tone[1]},${m.tone[2]},${a})`;
            ctx.fillRect(Math.round(sx), Math.round(sy), s, s);
        }
        ctx.restore();
    }
}

/**
 * Draws the cat, as an ACTOR rather than as another thing Critters paints.
 *
 * Satisfying `World`'s actor contract is what buys depth sorting and a contact
 * shadow for free: the cat walks behind a crate and in front of the next one on
 * exactly the same terms as the character does, which is the difference between
 * an animal in the scene and a decal over it.
 *
 * Each pose declares its own height in reference px, so the cat stays one size
 * whichever picture is on screen — a sitting cat is taller than a walking one
 * and both are taller than a sleeping one, and scaling three different images
 * to the same number would say otherwise.
 */
export class CatActor {
    /** Reference-pixel heights per pose. A sitting cat is about 40cm. */
    static HEIGHTS = { sit: 42, walk: 32, curl: 23 };

    /**
     * @param {Critters} critters
     * @param {Record<string, HTMLImageElement>} images - keyed by pose
     */
    constructor(critters, images) {
        this.critters = critters;
        this.images = images;
        this.isSprite = true;
        this.visible = true;
        this.id = 'cat';
    }

    get cat() { return this.critters.cat; }
    get loaded() { return !!(this.cat && this.images[this.cat.pose]); }
    get worldX() { return this.cat ? this.cat.x : 0; }
    get z() { return this.cat ? this.cat.z : 0.5; }

    get image() { return this.cat ? this.images[this.cat.pose] : null; }

    get worldScale() {
        const img = this.image;
        if (!img) return 1;
        return CatActor.HEIGHTS[this.cat.pose] / img.height;
    }

    /** The shadow is sized off this; see World.drawActor. */
    get frameWidth() {
        const img = this.image;
        return img ? img.width : 0;
    }

    /**
     * Part of the actor contract; the cat has nothing to do here.
     *
     * `World.update` advances every actor, because the character is a `Sprite`
     * with frames to step. The cat's behaviour is driven by `Critters.update`
     * along with the rest of the wildlife, so this exists to be called.
     */
    update() {}

    draw(ctx) {
        const img = this.image;
        if (!img || !this.visible) return;

        const w = img.width * this.scale;
        const h = img.height * this.scale;
        // The art is drawn facing right; left is mirrored, exactly as the
        // character is.
        const flip = this.cat.facing < 0;

        ctx.save();
        if (flip) {
            ctx.translate(this.x, 0);
            ctx.scale(-1, 1);
            ctx.drawImage(img, -w / 2, this.y - h, w, h);
        } else {
            ctx.drawImage(img, this.x - w / 2, this.y - h, w, h);
        }
        ctx.restore();
    }
}
