/**
 * Writes the preload hints into `index.html`.
 *
 *   node scripts/build_preload.mjs           rewrite the block
 *   node scripts/build_preload.mjs --check   exit 1 if it has drifted
 *
 * THE PROBLEM
 * -----------
 * A browser discovers ES modules level by level. It fetches `world-main.js`,
 * parses it, learns about twenty-two more, fetches those, parses them, learns
 * about five more, and so on. The graph here is five levels deep, so that is
 * five round trips — 600ms on a phone — before a single line of the site's own
 * code runs, and the artwork cannot even be REQUESTED until it does.
 *
 * Measured by `npm run budget`: 687ms of a 1,276ms load, in a graph whose
 * compressed bytes are only 104KB. Almost all of it was latency.
 *
 * THE FIX
 * -------
 * `modulepreload` tells the browser about the whole graph while it is still
 * parsing the HTML, so all thirty-two are fetched at once and the depth stops
 * mattering. `preload as="image"` does the same for the artwork that is
 * certainly needed, so it downloads DURING the module phase instead of after
 * it.
 *
 * WHY GENERATED
 * -------------
 * Because a hand-written list of thirty-two module paths is wrong the first
 * time anyone adds an import, and wrong silently: a missing hint is not an
 * error, it is just the old load time creeping back. CI checks it, the same way
 * it checks the post index and the sitemap.
 *
 * Only the CERTAIN art is preloaded. A hint for something the page turns out
 * not to need is worse than no hint — it competes for bandwidth with what the
 * page does need — so this lists the backdrops and the character sheet, which
 * are the largest files and are on screen in the first frame, and leaves the
 * two hundred prop slots to the loader.
 */
import { readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { dirname, join, normalize, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { scenes, START_SCENE } from '../js/config/scenes.js';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const HTML = join(ROOT, 'index.html');
const ENTRY = 'js/world-main.js';

const BEGIN = '<!-- preload:begin -->';
const END = '<!-- preload:end -->';

const check = process.argv.includes('--check');

/** Every module reachable from the entry, deepest-discovered first. */
function moduleGraph(entry) {
    const seen = new Map();

    const walk = (file, depth) => {
        const key = normalize(join(ROOT, file));
        const hit = seen.get(key);
        if (hit) { hit.depth = Math.min(hit.depth, depth); return; }

        let source;
        try { source = readFileSync(key, 'utf8'); } catch { return; }
        seen.set(key, { depth });

        const rel = (spec) => relative(ROOT, join(dirname(key), spec));

        for (const m of source.matchAll(
            /^\s*(?:import|export)[^'"]*from\s*['"](\.[^'"]+)['"]/gm)) {
            walk(rel(m[1]), depth + 1);
        }
        for (const m of source.matchAll(/^\s*import\s*['"](\.[^'"]+)['"]/gm)) {
            walk(rel(m[1]), depth + 1);
        }
    };

    walk(entry, 0);

    // Ordered by discovery depth, then by path, so the browser is told about
    // the entry's own direct imports first and the file is stable to diff.
    return [...seen.entries()]
        .map(([file, v]) => ({ path: relative(ROOT, file).split(sep).join('/'), depth: v.depth }))
        .sort((a, b) => a.depth - b.depth || a.path.localeCompare(b.path));
}

/** The art that is certainly on screen in the first frame. */
function criticalImages() {
    const manifest = scenes.find(s => s.id === START_SCENE).manifest;
    const out = [];

    // The backdrops are the full-width plates behind everything, and the
    // largest files in the world.
    for (const b of manifest.backdrops || []) {
        if (b.src) out.push(b.src.replace(/^\.\//, ''));
    }
    // The character is the one thing a visitor is guaranteed to look at.
    if (manifest.actor) out.push(manifest.actor.src.replace(/^\.\//, ''));

    return out
        .filter(f => existsSync(join(ROOT, f)))
        .sort((a, b) => statSync(join(ROOT, b)).size - statSync(join(ROOT, a)).size);
}

function render() {
    const modules = moduleGraph(ENTRY);
    const images = criticalImages();

    const lines = [
        BEGIN,
        '<!--',
        '  GENERATED by scripts/build_preload.mjs. Run `npm run preload`.',
        '',
        '  The browser discovers ES modules one level at a time, so a graph five',
        '  deep costs five round trips before any of this site\'s code runs — and',
        '  the artwork cannot be requested until it does. These hints let the',
        '  whole graph be fetched at once, and start the largest images while the',
        '  modules are still arriving.',
        '-->',
        ...modules.map(m => `<link rel="modulepreload" href="${m.path}">`),
        '',
        ...images.map(f => `<link rel="preload" as="image" href="${f}">`),
        END
    ];

    return lines.join('\n');
}

const html = readFileSync(HTML, 'utf8');
const block = render();

const from = html.indexOf(BEGIN);
const to = html.indexOf(END);

if (from === -1 || to === -1) {
    console.error(`index.html has no ${BEGIN} / ${END} markers to write between.`);
    process.exit(1);
}

const updated = html.slice(0, from) + block + html.slice(to + END.length);
const same = (a, b) => a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n');

const modules = moduleGraph(ENTRY).length;
const images = criticalImages().length;

if (check) {
    if (same(html, updated)) {
        console.log(`preload hints ok: ${modules} modules, ${images} images`);
        process.exit(0);
    }
    console.error('\nindex.html preload hints do not match the module graph.');
    console.error('Run `npm run preload` and commit the result.\n');
    process.exit(1);
}

if (same(html, updated)) {
    console.log(`preload hints unchanged: ${modules} modules, ${images} images`);
} else {
    writeFileSync(HTML, updated);
    console.log(`preload hints written: ${modules} modules, ${images} images`);
}
