/**
 * Generates `sitemap.xml` and `robots.txt`.
 *
 * A sitemap listing two pages is trivial to write by hand and guaranteed to be
 * wrong within a month, because posts are added and nobody remembers. It is
 * derived from the same post index every listing on the site reads, so adding a
 * post adds a sitemap entry.
 *
 * Usage:
 *   node scripts/build_site_meta.mjs           write both files
 *   node scripts/build_site_meta.mjs --check   exit 1 if they have drifted
 *
 * `--check` is what CI runs, for the same reason as the post index: a push is a
 * deploy, so a stale generated file is a live one.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { site } from '../js/config/site.js';
import { posts } from '../js/config/posts.js';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const check = process.argv.includes('--check');

/** The site's own origin, with no trailing slash. */
const BASE = site.baseUrl.replace(/\/$/, '');

/**
 * Everything with a URL.
 *
 * A post is a query string on `blog.html` rather than a path of its own, which
 * is what a static host without rewrites gives you. Crawlers index those
 * perfectly well; they are simply not pretty.
 */
function urls() {
    const newest = posts.reduce((a, p) => (p.date > a ? p.date : a), '');

    return [
        { loc: `${BASE}/`, changefreq: 'monthly', priority: '1.0' },
        { loc: `${BASE}/blog.html`, changefreq: 'weekly', priority: '0.8', lastmod: newest },
        ...posts.map(p => ({
            loc: `${BASE}/blog.html?id=${encodeURIComponent(p.id)}`,
            changefreq: 'yearly',
            priority: '0.6',
            lastmod: p.date
        }))
    ];
}

const xml = (s) => String(s).replace(/[&<>"']/g,
    c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]));

function sitemap() {
    const entries = urls().map(u => [
        '  <url>',
        `    <loc>${xml(u.loc)}</loc>`,
        ...(u.lastmod ? [`    <lastmod>${xml(u.lastmod)}</lastmod>`] : []),
        `    <changefreq>${u.changefreq}</changefreq>`,
        `    <priority>${u.priority}</priority>`,
        '  </url>'
    ].join('\n')).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build_site_meta.mjs. Run \`npm run meta\`. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function robots() {
    return `# GENERATED by scripts/build_site_meta.mjs. Run \`npm run meta\`.
#
# Everything is public and there is nothing to hide. The one directory worth
# keeping out of an index is the art pipeline's intermediates, which are large,
# numerous and of no interest to anybody arriving from a search.

User-agent: *
Allow: /
Disallow: /assets/city/raw/

Sitemap: ${BASE}/sitemap.xml
`;
}

const files = [
    ['sitemap.xml', sitemap()],
    ['robots.txt', robots()]
];

const same = (a, b) => a != null && a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n');

let drifted = false;

for (const [name, content] of files) {
    const path = join(ROOT, name);
    const current = (() => {
        try { return readFileSync(path, 'utf8'); } catch { return null; }
    })();

    if (same(current, content)) {
        if (!check) console.log(`${name} unchanged`);
        continue;
    }

    if (check) {
        console.error(`${name} is out of date.`);
        drifted = true;
    } else {
        writeFileSync(path, content);
        console.log(`${name} written`);
    }
}

if (check) {
    if (drifted) {
        console.error('\nRun `npm run meta` and commit the result.\n');
        process.exit(1);
    }
    console.log(`site meta ok: ${urls().length} urls`);
}
